name: Update apps

on:
  workflow_dispatch:
jobs:
  update-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3
      - uses: nanasess/setup-chromedriver@v2
      - name: Fetch and patch apks
        run: uv run --with . repatcher patch-all

      - name: Make a folder where I put the apks
        run: |
          mkdir -p /tmp/RESULT
          mv /tmp/revancedbot/patched_apks/*.apk /tmp/RESULT

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/RESULT
